#!/bin/bash
# scripts/load-env.sh
# Fetches all local dev secrets from GCP Secret Manager and writes .env files.
#
# Prerequisites:
#   gcloud auth application-default login
#
# Usage:
#   ./scripts/load-env.sh
#   ./scripts/load-env.sh --project your-firebase-project-id

set -e

PROJECT="${GCP_PROJECT_ID:-laneconductor-site}"

# Allow override via --project flag
while [[ $# -gt 0 ]]; do
  case $1 in
    --project) PROJECT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

echo "Loading secrets from GCP Secret Manager (project: $PROJECT)..."

fetch() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT"
}

# ── Root .env ────────────────────────────────────────────────────────────────
cat > .env << EOF
# Auto-generated by scripts/load-env.sh — do not edit manually
DB_HOST=127.0.0.1
DB_PASSWORD=postgres  # local dev default — not a secret

CLOUD_DB_HOST=$(fetch LOCAL_CLOUD_DB_HOST)
CLOUD_DB_PORT=5432
CLOUD_DB_NAME=postgres
CLOUD_DB_USER=$(fetch LOCAL_CLOUD_DB_USER)
CLOUD_DB_PASSWORD=$(fetch CLOUD_DB_PASSWORD)
CLOUD_DB_SSL=true
GCP_PROJECT_ID=$(fetch GCP_PROJECT_ID)
EOF
echo "✅ .env"

# ── ui/.env.remote ───────────────────────────────────────────────────────────
cat > ui/.env.remote << EOF
# Auto-generated by scripts/load-env.sh — do not edit manually
VITE_FIREBASE_API_KEY=$(fetch VITE_FIREBASE_API_KEY)
VITE_FIREBASE_AUTH_DOMAIN=$(fetch VITE_FIREBASE_AUTH_DOMAIN)
VITE_FIREBASE_PROJECT_ID=$(fetch VITE_FIREBASE_PROJECT_ID)
VITE_FIREBASE_STORAGE_BUCKET=$(fetch VITE_FIREBASE_STORAGE_BUCKET)
VITE_FIREBASE_MESSAGING_SENDER_ID=$(fetch VITE_FIREBASE_MESSAGING_SENDER_ID)
VITE_FIREBASE_APP_ID=$(fetch VITE_FIREBASE_APP_ID)
EOF
echo "✅ ui/.env.remote"

echo ""
echo "Done. Run 'source .env' or restart your dev server to pick up changes."
